### ISSUE TITLE
Connect backend with frontend

### ISSUE THREAD

**Issue by david-llamas-roman** [david-llamas-roman/davidllamasroman.com#4]
I need put the content of, for example, projects collection of mongodb database in 'projects' section

**Comment by Nandini1071** [comment]
Hi is this issue still open, if yes then what is the requirement ?

**Comment by david-llamas-roman** [comment]
> Hi is this issue still open, if yes then what is the requirement ?

Hi,

The issue is still opening, but I assigned it to myself, because this is my personal website / portfolio and this is the first time that I tried to make a full website with frontend and backend.

The issue process is only to get projects from a mongoDB database that I am creating too and put them in the 'projects' section. Also, I want to do that with companies that I have been to and the 'experience' section.

I am on holidays until this thursday, then I will work on this. Sorry for the inconvenience, when I have the first stable / production version of the website, I will accept contributions, but at the moment those 2 issues that I have open are assigned to me.

Anyway, thanks for asking.
